/**
 * Promo Code Pool System
 *
 * Automatically assigns one-time-use promo codes to new users after email verification.
 * Uses localStorage for client-side tracking (MVP approach).
 *
 * Launch codes expire: April 30, 2026
 */

// 500 launch promo codes - each gives one free listing
const PROMO_CODE_POOL: string[] = [
  "LAUNCH-FB55YP", "LAUNCH-B9KZ7W", "LAUNCH-EJBVY8", "LAUNCH-U6D242", "LAUNCH-KQUEBC",
  "LAUNCH-QGDPLU", "LAUNCH-YC56ZD", "LAUNCH-TC6ASM", "LAUNCH-RQX2Q5", "LAUNCH-KC3LW9",
  "LAUNCH-HQJMU4", "LAUNCH-CSL4JD", "LAUNCH-UJ5G66", "LAUNCH-FL25SE", "LAUNCH-ABZRFZ",
  "LAUNCH-UULTM8", "LAUNCH-QW5LZ4", "LAUNCH-MEFGEA", "LAUNCH-WEA3QR", "LAUNCH-K5GB2P",
  "LAUNCH-ZK5D37", "LAUNCH-3KAGCJ", "LAUNCH-HWYQHH", "LAUNCH-FT47JD", "LAUNCH-3X3WDP",
  "LAUNCH-5PEVU8", "LAUNCH-2TLJHQ", "LAUNCH-W4HED3", "LAUNCH-NZ6Q2R", "LAUNCH-9ZBC7Z",
  "LAUNCH-3AGFGM", "LAUNCH-HAVVN2", "LAUNCH-CMVJ87", "LAUNCH-V6ZM79", "LAUNCH-8XPT77",
  "LAUNCH-SKZWSR", "LAUNCH-NUUEQ6", "LAUNCH-U65HC8", "LAUNCH-FXQ5SS", "LAUNCH-Y6NMNE",
  "LAUNCH-8XAAXN", "LAUNCH-7W7S9Q", "LAUNCH-XNS5NF", "LAUNCH-369PJD", "LAUNCH-74RZSW",
  "LAUNCH-C74TLQ", "LAUNCH-JUVYDA", "LAUNCH-VJS5SF", "LAUNCH-88RT52", "LAUNCH-EC6CMZ",
  "LAUNCH-KXPCK4", "LAUNCH-NNBSBT", "LAUNCH-XQD6BB", "LAUNCH-D2KLR6", "LAUNCH-77Q3WT",
  "LAUNCH-7T67QL", "LAUNCH-HBP6FS", "LAUNCH-N5P3JL", "LAUNCH-JH34J3", "LAUNCH-D25EMT",
  "LAUNCH-E3BZVH", "LAUNCH-YA8DDC", "LAUNCH-RSN75X", "LAUNCH-5JCWC7", "LAUNCH-W762LN",
  "LAUNCH-HTG5S9", "LAUNCH-3E64S7", "LAUNCH-ELSEG3", "LAUNCH-CC4PYW", "LAUNCH-UBG32F",
  "LAUNCH-9WJMCE", "LAUNCH-HUYW8M", "LAUNCH-B9HFAY", "LAUNCH-D44T59", "LAUNCH-N4Z8HJ",
  "LAUNCH-UNLQNW", "LAUNCH-3RYLYS", "LAUNCH-C9CYYD", "LAUNCH-J9PMX8", "LAUNCH-PUNNUX",
  "LAUNCH-7TMJVP", "LAUNCH-DUJF3E", "LAUNCH-E7LSMY", "LAUNCH-8Z6REV", "LAUNCH-7XSSQX",
  "LAUNCH-7R5K8F", "LAUNCH-AGPSDF", "LAUNCH-2V8G7L", "LAUNCH-KLSWKR", "LAUNCH-WFKKMZ",
  "LAUNCH-43X72K", "LAUNCH-J4U7FN", "LAUNCH-TA7GJU", "LAUNCH-5EEHU9", "LAUNCH-8GY58K",
  "LAUNCH-B6YSVZ", "LAUNCH-N46ZEH", "LAUNCH-CMBTVS", "LAUNCH-3YF4UU", "LAUNCH-V5LLPB",
  "LAUNCH-XFCZPX", "LAUNCH-R7MJZF", "LAUNCH-8DQ93M", "LAUNCH-P3Q4S7", "LAUNCH-FLYEN6",
  "LAUNCH-2LNRDQ", "LAUNCH-F6LG8P", "LAUNCH-EUMU4X", "LAUNCH-TA56NZ", "LAUNCH-UNWVLN",
  "LAUNCH-FU7CTP", "LAUNCH-7VNYSR", "LAUNCH-R4KN9B", "LAUNCH-NZKBE4", "LAUNCH-3R5BGY",
  "LAUNCH-Y6KUGE", "LAUNCH-TDYBN3", "LAUNCH-SUVJV5", "LAUNCH-XXKE2W", "LAUNCH-HLZXZE",
  "LAUNCH-BGV2EB", "LAUNCH-4SF74P", "LAUNCH-K8GJY4", "LAUNCH-P69Q8L", "LAUNCH-8YVZU6",
  "LAUNCH-KMXZZF", "LAUNCH-FS8CKB", "LAUNCH-XQHFER", "LAUNCH-4FVVZ6", "LAUNCH-KAF2QY",
  "LAUNCH-GEESRF", "LAUNCH-ZKSUYY", "LAUNCH-4SBEZS", "LAUNCH-GFVE7Z", "LAUNCH-L7NWB5",
  "LAUNCH-Y5PKR3", "LAUNCH-3HNVBS", "LAUNCH-2SSC8R", "LAUNCH-RB7DSB", "LAUNCH-5A3ZWC",
  "LAUNCH-AVMAE5", "LAUNCH-T8YT22", "LAUNCH-7RLZXC", "LAUNCH-9WPHNT", "LAUNCH-TDUE7M",
  "LAUNCH-EBMBKE", "LAUNCH-6WVCP4", "LAUNCH-PRNZMU", "LAUNCH-RAGNVY", "LAUNCH-XQGR6G",
  "LAUNCH-VA9YS8", "LAUNCH-6MVSNF", "LAUNCH-7934GZ", "LAUNCH-SPQS5J", "LAUNCH-PMXB7D",
  "LAUNCH-XPJ7JE", "LAUNCH-3XPEDE", "LAUNCH-EDUMLU", "LAUNCH-QS4TPU", "LAUNCH-NYBBT3",
  "LAUNCH-GW96BN", "LAUNCH-2R7TZN", "LAUNCH-B4BB6M", "LAUNCH-9BAU6U", "LAUNCH-D5N4UL",
  "LAUNCH-LDLBVS", "LAUNCH-MHUT8V", "LAUNCH-5SWMFA", "LAUNCH-UZ47RX", "LAUNCH-M54MT3",
  "LAUNCH-7CM7SZ", "LAUNCH-GTAUV8", "LAUNCH-PBPXNY", "LAUNCH-K9ULQG", "LAUNCH-S2FLLD",
  "LAUNCH-V76WSP", "LAUNCH-XD4TSZ", "LAUNCH-6QCG2A", "LAUNCH-EYTP8H", "LAUNCH-JGDXN7",
  "LAUNCH-6RS7E7", "LAUNCH-AJJQSG", "LAUNCH-UHZ8X4", "LAUNCH-ENQHK2", "LAUNCH-P7N63L",
  "LAUNCH-F2GYXZ", "LAUNCH-A66YU3", "LAUNCH-Y286DX", "LAUNCH-WA23X4", "LAUNCH-GS5HVB",
  "LAUNCH-MKSFKZ", "LAUNCH-Q6Y2SV", "LAUNCH-WYCJER", "LAUNCH-WU6HTP", "LAUNCH-RBH5L3",
  "LAUNCH-C65K93", "LAUNCH-E9P77Z", "LAUNCH-64VD8C", "LAUNCH-5K2X4B", "LAUNCH-6CNDPV",
  "LAUNCH-26N9LD", "LAUNCH-44KRNV", "LAUNCH-9Q3QKL", "LAUNCH-4EYEDQ", "LAUNCH-N9M63M",
  "LAUNCH-9E248J", "LAUNCH-YLENG7", "LAUNCH-CXUATF", "LAUNCH-CX2FLY", "LAUNCH-YP4YYN",
  "LAUNCH-NE5D6L", "LAUNCH-MSCE2A", "LAUNCH-2TZZJ6", "LAUNCH-UZUDC7", "LAUNCH-BGMGVS",
  "LAUNCH-JCQPPK", "LAUNCH-LPATKX", "LAUNCH-22DGCF", "LAUNCH-RH5ASU", "LAUNCH-D8S2G3",
  "LAUNCH-WKTC8U", "LAUNCH-BR3CZR", "LAUNCH-ZA8F9R", "LAUNCH-L3GNCF", "LAUNCH-YVBUN4",
  "LAUNCH-52XE2Q", "LAUNCH-CHYKHA", "LAUNCH-FGTUP4", "LAUNCH-639CPK", "LAUNCH-FA2NKL",
  "LAUNCH-99GX64", "LAUNCH-Q9L9CF", "LAUNCH-62Y9F7", "LAUNCH-23YGSS", "LAUNCH-JE8KJB",
  "LAUNCH-G8HAET", "LAUNCH-D2LA37", "LAUNCH-BUH9TR", "LAUNCH-VSDT3U", "LAUNCH-3HAARV",
  "LAUNCH-72365Q", "LAUNCH-67ZRHL", "LAUNCH-S2UNAJ", "LAUNCH-AR5AC2", "LAUNCH-TH4LVH",
  "LAUNCH-L3E539", "LAUNCH-3Y6Y4R", "LAUNCH-JSCWMF", "LAUNCH-TUX3VR", "LAUNCH-KS4MVE",
  "LAUNCH-G3XLX3", "LAUNCH-QH7NDQ", "LAUNCH-BVNFX9", "LAUNCH-2TJEEY", "LAUNCH-JG6UKE",
  "LAUNCH-VXCQQ2", "LAUNCH-Q67B9K", "LAUNCH-4N46HB", "LAUNCH-4DYPA3", "LAUNCH-TS2KNY",
  "LAUNCH-EXAPXP", "LAUNCH-UH54JK", "LAUNCH-2YM3P2", "LAUNCH-GKBJ94", "LAUNCH-N29EPU",
  "LAUNCH-MPE9NS", "LAUNCH-NZMNT7", "LAUNCH-XHZR6J", "LAUNCH-CP9YD8", "LAUNCH-Y689F5",
  "LAUNCH-MJ9RSH", "LAUNCH-97NPC8", "LAUNCH-5YHVAV", "LAUNCH-SNNLJN", "LAUNCH-6ZAS96",
  "LAUNCH-XV2KXW", "LAUNCH-376E7E", "LAUNCH-GLZNKB", "LAUNCH-BVRA23", "LAUNCH-2YD7YZ",
  "LAUNCH-QSJQZ4", "LAUNCH-KAU8R8", "LAUNCH-L6N4TP", "LAUNCH-UUBAQN", "LAUNCH-A2HPEV",
  "LAUNCH-QPG77S", "LAUNCH-V8W2T3", "LAUNCH-H2NXFM", "LAUNCH-PUNTDP", "LAUNCH-38HHPK",
  "LAUNCH-66E2F6", "LAUNCH-9VS3G6", "LAUNCH-P4KDYY", "LAUNCH-4SVX6E", "LAUNCH-B94JR4",
  "LAUNCH-232BMG", "LAUNCH-YQKGFK", "LAUNCH-L3WQEX", "LAUNCH-REJSV3", "LAUNCH-6HV9PP",
  "LAUNCH-4HCJ8Y", "LAUNCH-XHZL67", "LAUNCH-649EN9", "LAUNCH-SJDF7T", "LAUNCH-3P48R4",
  "LAUNCH-ZLGYPC", "LAUNCH-EZ3D7C", "LAUNCH-2JR43B", "LAUNCH-WEZWLV", "LAUNCH-UL22MX",
  "LAUNCH-A2NSTN", "LAUNCH-M8B7DH", "LAUNCH-96FYKK", "LAUNCH-ZJ82MB", "LAUNCH-57ND5X",
  "LAUNCH-CASG39", "LAUNCH-Y665F2", "LAUNCH-2U75AH", "LAUNCH-R5F6KJ", "LAUNCH-MMKNZU",
  "LAUNCH-PF9DNA", "LAUNCH-EUBPBF", "LAUNCH-VSB4FR", "LAUNCH-ERE6AZ", "LAUNCH-SBTBV7",
  "LAUNCH-LS5BYN", "LAUNCH-RATDAK", "LAUNCH-C8PZ8J", "LAUNCH-PW3TN2", "LAUNCH-QEFX6U",
  "LAUNCH-VLYF5B", "LAUNCH-A54BS4", "LAUNCH-GECDD9", "LAUNCH-RNNTQ4", "LAUNCH-XZS8SA",
  "LAUNCH-VXN7FV", "LAUNCH-5HKAQ7", "LAUNCH-ZTX4B7", "LAUNCH-LGBAAU", "LAUNCH-829QR5",
  "LAUNCH-JLGLB8", "LAUNCH-XZLFUT", "LAUNCH-MPYRBC", "LAUNCH-BA5VWG", "LAUNCH-8MLPXA",
  "LAUNCH-MAWPKR", "LAUNCH-FD43GV", "LAUNCH-A4UVM6", "LAUNCH-QRK95H", "LAUNCH-P2H2RW",
  "LAUNCH-XKWFF4", "LAUNCH-647LVW", "LAUNCH-DQCRPK", "LAUNCH-YTM9DX", "LAUNCH-55QQ24",
  "LAUNCH-R45NKJ", "LAUNCH-DTYHEB", "LAUNCH-SFJA4Y", "LAUNCH-8QP4SP", "LAUNCH-PQCSJ9",
  "LAUNCH-YC9JV3", "LAUNCH-UG6L9Y", "LAUNCH-26LAFP", "LAUNCH-TJ84BS", "LAUNCH-LJRG8T",
  "LAUNCH-AHH9UQ", "LAUNCH-L893XB", "LAUNCH-ZX8A2X", "LAUNCH-Q6AG3A", "LAUNCH-RMBWNU",
  "LAUNCH-ZBSVT7", "LAUNCH-RXQ2HT", "LAUNCH-BSNHY2", "LAUNCH-7V9TXV", "LAUNCH-8LB9Z6",
  "LAUNCH-Q928WN", "LAUNCH-WSMKZS", "LAUNCH-ATS4HZ", "LAUNCH-ASWPJT", "LAUNCH-3CFBAX",
  "LAUNCH-HRCCJU", "LAUNCH-KPMX2Q", "LAUNCH-9B7JTE", "LAUNCH-VV5VWC", "LAUNCH-4F3CJR",
  "LAUNCH-XXUY5X", "LAUNCH-7ZFBT6", "LAUNCH-6PFFCW", "LAUNCH-MF4YJT", "LAUNCH-L4L2BP",
  "LAUNCH-DPV3CA", "LAUNCH-YN2LYQ", "LAUNCH-KEHE29", "LAUNCH-Q2Z4Q3", "LAUNCH-E35U54",
  "LAUNCH-TFLEGY", "LAUNCH-KHH6L8", "LAUNCH-SJRTCV", "LAUNCH-M92K4C", "LAUNCH-4MHWPC",
  "LAUNCH-DLVTH5", "LAUNCH-FMB7L2", "LAUNCH-GZMMNK", "LAUNCH-7YYEDP", "LAUNCH-TSDN4W",
  "LAUNCH-E8LTCB", "LAUNCH-PSP9WJ", "LAUNCH-QFWRAE", "LAUNCH-73VWDZ", "LAUNCH-TDFM6X",
  "LAUNCH-38DNQK", "LAUNCH-2ZK6QH", "LAUNCH-JMYRLW", "LAUNCH-ZLXBJ2", "LAUNCH-3DEGQT",
  "LAUNCH-LBE36A", "LAUNCH-CBRQCU", "LAUNCH-6PMEQX", "LAUNCH-EFE2ZW", "LAUNCH-AXZFXE",
  "LAUNCH-DP59VP", "LAUNCH-DLWR5N", "LAUNCH-7T84ZH", "LAUNCH-8JRGXJ", "LAUNCH-PSZ28K",
  "LAUNCH-QW7XVU", "LAUNCH-TS5HC4", "LAUNCH-U6JL3C", "LAUNCH-MZVSN7", "LAUNCH-2VFFVW",
  "LAUNCH-Q6TFSU", "LAUNCH-7PBHMG", "LAUNCH-LW7F82", "LAUNCH-N7DREN", "LAUNCH-5PDRDE",
  "LAUNCH-35Q36F", "LAUNCH-KFFSXE", "LAUNCH-DL4GPR", "LAUNCH-CB9U9U", "LAUNCH-ST6J2V",
  "LAUNCH-P3E4G7", "LAUNCH-ETXAU5", "LAUNCH-7XQ6JX", "LAUNCH-9HGYH2", "LAUNCH-ZNGLC7",
  "LAUNCH-K544D6", "LAUNCH-7YDXLY", "LAUNCH-A275US", "LAUNCH-NV8YFF", "LAUNCH-TCL3CT",
  "LAUNCH-TNW569", "LAUNCH-Z7Y8SJ", "LAUNCH-7ZWL8T", "LAUNCH-NLC9DJ", "LAUNCH-Y9G57N",
  "LAUNCH-JV5PPV", "LAUNCH-PC8RK8", "LAUNCH-Y4Z2JU", "LAUNCH-GJCWQM", "LAUNCH-X9F6GH",
  "LAUNCH-CTH8QX", "LAUNCH-X5526B", "LAUNCH-CN5ZMS", "LAUNCH-RCSP6Q", "LAUNCH-7BD6GN",
  "LAUNCH-MVKECU", "LAUNCH-QXPR6R", "LAUNCH-VVXBWL", "LAUNCH-G2HJGQ", "LAUNCH-Y4TLQQ",
  "LAUNCH-XY78GN", "LAUNCH-S86WRN", "LAUNCH-2V9Z4F", "LAUNCH-4KAM2T", "LAUNCH-ZMBCJE",
  "LAUNCH-UJRTAG", "LAUNCH-JZGA4X", "LAUNCH-6KBRE7", "LAUNCH-59QN34", "LAUNCH-7656DD",
  "LAUNCH-DFCNPJ", "LAUNCH-EPREVD", "LAUNCH-T7EM7Z", "LAUNCH-7SAQAD", "LAUNCH-DQW2CE",
  "LAUNCH-QVP8DB", "LAUNCH-SFVZ9C", "LAUNCH-DJJ5ME", "LAUNCH-8L3M8H", "LAUNCH-2K6SRY",
  "LAUNCH-KB8APF", "LAUNCH-3XE5VU", "LAUNCH-BNCYFG", "LAUNCH-TW3DNW", "LAUNCH-X5FL5L",
  "LAUNCH-WWDSYR", "LAUNCH-J2HY7X", "LAUNCH-RUEWSB", "LAUNCH-JPTUV3", "LAUNCH-GUPEJ9",
];

const STORAGE_KEY = 'ausplates_promo_assignments';

interface PromoAssignments {
  assignedCodes: Record<string, string>; // userId -> code
  nextIndex: number; // Next code to assign from pool
}

/**
 * Get current assignments from localStorage
 */
function getAssignments(): PromoAssignments {
  if (typeof window === 'undefined') {
    return { assignedCodes: {}, nextIndex: 0 };
  }

  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      return JSON.parse(stored);
    }
  } catch (e) {
    console.error('Failed to read promo assignments:', e);
  }

  return { assignedCodes: {}, nextIndex: 0 };
}

/**
 * Save assignments to localStorage
 */
function saveAssignments(assignments: PromoAssignments): void {
  if (typeof window === 'undefined') return;

  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(assignments));
  } catch (e) {
    console.error('Failed to save promo assignments:', e);
  }
}

/**
 * Assign a promo code to a user
 * - If user already has a code, returns their existing code
 * - If no codes remaining, returns null
 * - Otherwise assigns the next available code
 */
export function assignCodeToUser(userId: string): string | null {
  if (!userId) return null;

  const assignments = getAssignments();

  // Check if user already has a code
  if (assignments.assignedCodes[userId]) {
    return assignments.assignedCodes[userId];
  }

  // Check if we have codes remaining
  if (assignments.nextIndex >= PROMO_CODE_POOL.length) {
    return null; // Pool exhausted
  }

  // Assign next code
  const code = PROMO_CODE_POOL[assignments.nextIndex];
  assignments.assignedCodes[userId] = code;
  assignments.nextIndex++;

  saveAssignments(assignments);

  return code;
}

/**
 * Get the code assigned to a user (without assigning a new one)
 */
export function getUserCode(userId: string): string | null {
  if (!userId) return null;

  const assignments = getAssignments();
  return assignments.assignedCodes[userId] || null;
}

/**
 * Check if the code pool is exhausted
 */
export function isPoolExhausted(): boolean {
  const assignments = getAssignments();
  return assignments.nextIndex >= PROMO_CODE_POOL.length;
}

/**
 * Get pool statistics
 */
export function getPoolStats(): { total: number; assigned: number; remaining: number } {
  const assignments = getAssignments();
  return {
    total: PROMO_CODE_POOL.length,
    assigned: assignments.nextIndex,
    remaining: PROMO_CODE_POOL.length - assignments.nextIndex,
  };
}
